<?php /* Template Name: Algemenevoorwaarden */ ?>
<?php get_header(); ?>

<section class="c-privacyverklaring grid-container">
        <h1>Algemene voorwaarden</h1>
        <p>www.zeepfabriek.be</p>
        <br>
        <p>1. Behoudens andersluidend schriftelijk beding, is elk aanbod en elke, ook toekomstige, overeenkomst beheerst door deze algemene voorwaarden, die er integraal deel van uitmaken en die van rechtswege voorrang hebben op de aankoop- en betalingsvoorwaarden van de klant. Iedere afwijking van deze algemene voorwaarden kan slechts aan ons worden tegengeworpen, indien wij daar voorafgaand, uitdrukkelijk en schriftelijk onze instemming mee hebben betuigd.</p>
        <br>
        <p>2. Alle prijsoffertes of voorstellen zijn vrijblijvend en zonder verbintenis van onzentwege. De door de klant via de website geplaatste bestelling en / of de bestelling gedaan in elektronische vorm, wordt door ons steeds schriftelijk bevestigd binnen een zo kort mogelijke termijn. De overeenkomst komt slechts tot stand nadat wij de geplaatste bestelling schriftelijk bevestigen via e-mail.</p>
        <br>
        <p>3. De prijzen van de goederen die via de website kunnen worden besteld zijn steeds inclusief BTW. Zolang geen overeenkomst tot stand is gekomen, behouden wij het recht voor om de prijzen van de goederen te wijzigen. Indien de klant kiest voor levering van de aangekochte goederen op een door hem gekozen plaats, worden kosten voor deze levering in rekening gebracht volgens de modaliteiten bepaald bij de bestelling. Indien de klant kiest voor afhaling in de winkel, worden geen extra kosten in rekening gebracht.</p>
        <br>
        <p>4. De klant – consument beschikt over een termijn van zeven werkdagen na de levering van de goederen waarbinnen hij aan de overeenkomst kan verzaken. Indien de klant – consument toepassing wenst te maken van zijn verzakingsrecht zal hij ons hiervan in kennis stellen binnen de voormelde termijn en onverwijld het nodige doen om de goederen onbeschadigd en ongebruikt terug te sturen. De klant – consument dient in te staan voor de kosten van het terugzenden. Indien de klant na de termijn van zeven werkdagen beslist om de overeenkomst eenzijdig op te zeggen, dan zal hij een forfaitaire schadevergoeding verschuldigd zijn van 25 % op de verkoopprijs.</p>
        <br>
        <p>5. Tenzij anders werd overeengekomen, is de klant verplicht de prijs en de eventuele bijkomende kosten te betalen binnen 8 dagen na levering. Bij gehele of gedeeltelijke niet-betaling op de vervaldag, zullen de openstaande facturen en / of bedragen van rechtswege en zonder voorafgaande ingebrekestelling rente geven berekend op basis van de Belgische wettelijke intrestvoet vermeerderd met 2 %, en zal het nog openstaande saldo, na een vergeefse ingebrekestelling, verhoogd worden met 12% van het bedrag.</p>
        <br>
        <p>6. Wij verbinden ons ertoe om de leveringen zo spoedig als mogelijk uit te voeren, en in ieder geval binnen de dertig dagen vanaf de dag volgend op die waarop de klant zijn bestelling aan ons heeft toegezonden. Indien de levering niet mogelijk is binnen de termijn van dertig dagen zullen wij de klant hiervan in kennis stellen uiterlijk dertig dagen nadat hij de bestelling geplaatst heeft. Behoudens ingeval van overmacht, bijv. ingeval van laattijdige levering door onze leverancier of om een andere reden onafhankelijk van onze wil, heeft de klant in dat geval het recht om de overeenkomst te ontbinden zonder kosten.</p>
        <br>
        <p>7. Behoudens andersluidende schriftelijke overeenkomst worden de goederen steeds door ons aan de klant geleverd “Af fabriek” (Ex Works of EXW). Ze worden vervoerd op risico en gevaar van de klant, zelfs wanneer overeengekomen is dat wij voor het vervoer instaan. De klant is onmiddellijk na levering verplicht de goede staat van de goederen na te zien en het aantal geleverde stuks te controleren.</p>
        <br>
        <p>8. De door ons aan de klant geleverde goederen blijven onze eigendom tot op het ogenblik dat alle door de klant verschuldigde bedragen met inbegrip van interesten en kosten, zijn betaald. Zolang de goederen niet volledig betaald werden, is het de klant verboden deze te verwerken, te verbruiken of te verkopen.</p>
        <br>
        <p>9. De bepalingen met betrekking tot de verkoop aan consumenten zoals opgenomen in het Burgerlijk Wetboek van (1649bis B.W. t.e.m. 1649octies B.W.) zijn van toepassing. Indien de klant meent dat de geleverde goederen niet conform zijn aan de overeenkomst zal hij ons hiervan in kennis stellen binnen een termijn van twee maanden nadat hij het gebrek aan conformiteit heeft vastgesteld.</p>
        <br>
        <p>10. De klant zal er rekening mee houden dat de goederen cosmetische producten zijn die uiteraard met de grootste zorg zijn samengesteld, doch dat hierdoor niet steeds het risico op een allergische reactie, dat uiteraard afhangt van persoon tot persoon, uitgesloten is. Bijgevolg verbindt de klant er zich toe om de specificaties en kenmerken, zoals opgenomen op onze website en / of de catalogus, nauwkeurig na te lezen en op basis hiervan te oordelen of de goederen geschikt zijn voor hem. In geen geval kunnen wij aansprakelijk gesteld worden voor eventuele gevolgschade ingeval van een allergische reactie indien de klant de gevolgen van het gebruik van de goederen zelf had kunnen inschatten en er dus op zich geen sprake is van een verkeerde samenstelling.</p>
        <br>
        <p>11. In geval van “vreemde oorzaak” (art. 1147 B.W.), zelfs wanneer zij niet tot blijvende en/of volstrekte onmogelijkheid van uitvoering leidt, zijn wij van rechtswege gemachtigd onze verbintenissen op te schorten of eenzijdig te annuleren, na de klant daarvan te hebben verwittigd. In dat geval kunnen wij in geen geval tot enige schadevergoeding gehouden zijn. Worden onder meer conventioneel als “vreemde oorzaak” beschouwd: oorlog, zelfs tussen derde landen, staking of lockout, politieke of sociale of economische onlusten, uitzonderlijke schaarste van grondstoffen of koopwaar, weersomstandigheden, brand, natuur- en/of andere rampen, overheidsbeslissingen die invloed hebben op de uitvoering van de verbintenissen, en dit zowel wanneer deze vreemde oorzaak zich voordoet bij ons als bij onze leveranciers.</p>
        <br>
        <p>12. Indien mocht blijken dat één of meerdere bedingen geheel of gedeeltelijk niet tegenover de klant kunnen ingeroepen worden, blijven de overige bepalingen van de overeenkomst onverminderd bestaan.</p>
        <br>
        <p>13. Ingeval van betwisting zijn uitsluitend bevoegd ratione loci de rechtbanken van het gerechtelijk arrondissement Kortrijk, tenzij zij wij hier uitdrukkelijk van afwijken. Iedere, zelfs buitenlandse klant, kan ons enkel dagvaarden voor de rechtbanken van onze zetel. De gebeurlijke uitgifte van wissels houdt geen schuldvernieuwing in en brengt derhalve geen enkele wijziging van de bevoegdheid noch van enige nadere bepaling van deze algemene voorwaarden met zich mee. Het Belgisch recht is van toepassing op deze algemene voorwaarden.</p>
    
    </section>

<?php get_footer(); ?>